In [1]:
import numpy as np

In [6]:
data = [[1,2,3],[4,5,6],[7,8,9]]
a=np.array(data)
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a.dtype

dtype('int32')

In [9]:
# 형변환
a = a.astype(np.float32)
# a = a.astype('float32')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [10]:
# 요소 접근
a[0][1]

2.0

In [11]:
a[0]

array([1., 2., 3.], dtype=float32)

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
# 1 9까지 리스트 만들고 3 * 3행렬로 보여줌
# reshape는 개수를 맞춰야함
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# 3차원으로 reshape
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [18]:
np.nan


nan

In [21]:
a = np.nan
type(a)

float

In [24]:
# 1부터 10까지 10개 생성
a = np.linspace(1, 10, 20)
a.reshape(4, 5)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

연산

In [26]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:

data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [28]:
# 행렬의 곱셈이아니라 각 요소들의 곱
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [29]:
#행렬의 곱
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

차원

In [32]:
#0차원 : 스칼라
a = np.array(1)
a
a.shape
#n차원을 알려줌
a.ndim

0

In [41]:
# 1차원 : 벡터
a = np.array([1,2,3,4,5])
a
# 5개의 형태를 가지고 있다
a.shape
a.ndim

1

In [45]:
# 2차원 : 행렬
a = np.array([[1,2,3],[4,5,6]])
a
# 2행 3열
a.shape
a.ndim

2

In [48]:
# 3차원이상의 다차원행렬을 tensorflow
a = np.array([[[1,2,3], [4,5,6]]])
a
a.shape
a.ndim

3

# matrix 유형

In [52]:
# 0부터 11까지 행렬
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [55]:
b = np.ones(12).reshape(3,4)
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
#영행렬
c = np.zeros(12).reshape(3,4)
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
#단위행렬
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
e = np.zeros([3,4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
e = np.zeros([3,4,2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [63]:
# empty는 zeros와 다르게 0에 가까운 수를 채운다
f = np.empty([2,3])
f

array([[2.12199579e-314, 6.36598737e-314, 1.06099790e-313],
       [1.48539705e-313, 1.90979621e-313, 2.33419537e-313]])

In [64]:
# 3*4행렬에 1000으로 다채우기
g = np.full((3, 4), 1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [65]:
# 2부터 10까지 6개를 동등한 간격으로 나누어줌
h = np.linspace(2,10,6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

# 집계함수

In [67]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [69]:
a[0, 1] = 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [70]:
# 평균
np.mean(a)

114.4

In [71]:
# 중앙값
np.median(a)

6.5

In [72]:
# 표준편차
np.std(a)

296.5485457728633

In [73]:
# 분산
np.var(a)

87941.04

In [74]:
# 열끼리 덧셈
np.sum(a,axis=0)

array([ 105, 1006,    9,   11,   13])

In [75]:
# 행끼리 덧셈
np.sum(a,axis=1)

array([1109,   35])

In [76]:
np.max(a)

1000

In [77]:
np.min(a)

2

In [78]:
import pandas as pd

In [80]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [91]:
s = pd.Series(data, index = ['a','b','c','d','e'])
a

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [83]:
a['b']

1

In [84]:
# 명시적 선언 인덱스의 값
a.loc['b']

1

In [86]:
# iloc[순서] 0번째  1번째의 값
a.iloc[1]

1

# 산술연산


In [92]:
s

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [96]:
s + 10
s - 10
s * 10
s ** 10
s / 5
s//5

a    0
b    0
c    0
d    0
e    0
dtype: int32

In [97]:
s

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [98]:
s > 15

a    False
b    False
c    False
d    False
e    False
dtype: bool

In [101]:
s[s>2]

d    3
e    4
dtype: int32

In [102]:
s.add(100)

a    100
b    101
c    102
d    103
e    104
dtype: int32

In [103]:
s.sub(100)

a   -100
b    -99
c    -98
d    -97
e    -96
dtype: int32

In [104]:
s.mul(100)

a      0
b    100
c    200
d    300
e    400
dtype: int32

In [105]:
s.div(100)

a    0.00
b    0.01
c    0.02
d    0.03
e    0.04
dtype: float64

In [106]:
s.mod(3)

a    0
b    1
c    2
d    0
e    1
dtype: int32

In [107]:
s.min()

0

In [108]:
s.max()

4

In [109]:
s.mean()

2.0

In [110]:
s.median()

2.0

In [111]:
s.std()

1.5811388300841898

In [112]:
s.var()

2.5

# DataFrame

In [114]:
rawData = np.random.randint(50,100,size = (4,3))
rawData

array([[94, 87, 81],
       [77, 72, 88],
       [89, 81, 58],
       [75, 57, 97]])